# When any change is pushed on master, it triggers a beta
# version release with the @next tag 
#
# When a tag is published, it triggers the release flow,
# which takes the version which is released and converts
# it into the @latest tag
name: Process master branch updates

on:
  push:
    branches:
      - master

jobs:
  push-to-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bhoos-devops
          git config user.email devops@bhoos.com
          echo -e "github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bhoos'
      - name: Install Dependencies and publish packages
        run: |
          yarn
          yarn patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}